spring.datasource.url=jdbc:postgresql://localhost:5438/bank
#http://localhost:8888/NativeReact
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate

# Уровень логирования для корневого логгера
logging.level.root=INFO

# Уровень логирования для конкретного пакета
logging.level.com.example.demo=DEBUG

# Файл для вывода логов
logging.file.name=logs/app.log
spring.sql.init.schema-locations=classpath*:db/schema.sql
spring.sql.init.data-locations=classpath*:db/data.sql
#Security configuration
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9080/realms/
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:9080/realms/master/protocol/openid-connect/certs
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml
logging.level.org.springframework.security=DEBUG

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

